### ISSUE TITLE
Completing Scenario #14 

### ISSUE THREAD

**Issue by BrotherChip** [dducro/gloomhaven-storyline#19]
Noticed when completing scenario #14 it doesn't allow the user to choose which of the scenarios they wish to unlock. Really great stuff otherwise. I've been wishing for something like this for a while now. Cheers!

**Comment by dducro** [comment]
Thanks for your suggestion, feedback is always welcome! :)

> The location numbers in the story text are just reminders. They themselves don't unlock anything.

https://boardgamegeek.com/thread/1722032/scenario-14-conclusion-spoilers
