### ISSUE TITLE
Wrong city event to unlock side scenario 81

### ISSUE THREAD

**Issue by the-nuclear-winter** [dducro/gloomhaven-storyline#22]
Clicking on scenario 81 (which my party has unlocked) I wanted to know what led to the unlock. You have city event 18 listed and looking at the card that comes up there is nothing to do with unlocking scenario 81 connected to that card. Its actually city event 17 that unlocks side scenario 81.

**Comment by dducro** [comment]
Thanks for pointing that out, fixed it :)
