### ISSUE TITLE
Scenario 37 not becoming available [Potential Spoilers]

### ISSUE THREAD

**Issue by nicholaskillin** [dducro/gloomhaven-storyline#25]
So I'm going to start by saying that I could totally be missing something, but I believe that scenario 37 should be available to us and it's not. Here is a link to our current setup.

https://gloomhaven-storyline.danield.nl/?choices=13_20&states=1_c-2_c-3_c-4_c-5_c-6_c-7_c-8_c-9_b-10_c-13_c-14_c-16_c-18_c-19_c-20_c-21_c-22_i-23_i-24_c-25_i-26_i-27_c-28_c-29_c-30_i-32_c-33_c-40_c-41_c-43_c-61_i-64_i-68_c-76_i-81_i-87_i

We completed scenario 43. Doing that should unlock 26 and 37. It also gives you the Water Breathing Global Achievement. 

The only requirement for scenario 37 is water breathing. So if you complete 43 I think 37 should automatically unlock. 

If I'm incorrect please let me know. 😆

**Comment by dducro** [comment]
Hey,

See the following post:
https://www.reddit.com/r/Gloomhaven/comments/80cq4h/question_about_adding_scenario_37_and/

Scenario 43 doesn't unlock any new scenarios. When you do unlock 37 you can immediately start it.
Unlocked scenarios are written below "new Locations" in the scenario book.

Hope this helps! :)

**Comment by nicholaskillin** [comment]
Good catch. Thanks for clarifying!
