### ISSUE TITLE
Scenario states should be more visual distinctive 

### ISSUE THREAD

**Issue by tomasvanrijsse** [dducro/gloomhaven-storyline#4]
we could do two improvements

1. Add colors for states
I'd suggest:
   - white: completed
   - green: unlocked & requirements met
   - orange: unlocked & requirements needed
   - white: blocked (the cross will say enough)

2. change line & arrow style to dotted/dashed and change it's color to match the scenario

**Comment by tomasvanrijsse** [comment]
We chose not to use colors to take the color blind into account.
But we could do use colors & patterns/textures to indicate scenario states.
Like the cross on the blocked scenario is the pattern but it can be red at the same time.

**Comment by tomasvanrijsse** [comment]
Suggestion from Thomas Everding:
https://boardgamegeek.com/thread/2398582/article/34423931#34423931

> thought of colors, too, but your colorblind-arguments beats it. But I guess as long as you have different styles and shapes, you can still add colors on top: white (or green): open; gray: completed; red: locked; yellow: requirement not met
> 
> What I found in the app was: normal borders (open), thick borders (completed), stars (requirement needed), and crossed scenario numbers (blocked).
> 
> My suggestions would be:
> * use dashed borders and dashed lines to have a better dirrerence between open and completed scenarios
> * use the thick border on open scenarios (that is, what I want to find) an maybe a brighter (more white-ish) color

**Comment by dducro** [comment]
I'll experiment with colors/patterns, It might be a toggle to turn on/off.

**Comment by dducro** [comment]
I've decided on:
red with x = blocked
orange with ! = required
green with thick border = incomplete
white = completed
